// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_ikhLuRa6f402i828yEX5dhrrj3n2NBQ',
    appId: '1:1046328657587:web:054f76f33b94f6b66192c6',
    messagingSenderId: '1046328657587',
    projectId: 'fir-report-17f69',
    authDomain: 'fir-report-17f69.firebaseapp.com',
    storageBucket: 'fir-report-17f69.firebasestorage.app',
    measurementId: 'G-HXH0T5QN1C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLWT8nDyoy5k-KIt-_daThVw9ZmhGrtBY',
    appId: '1:1046328657587:android:cef2f6f5a0f6f36f6192c6',
    messagingSenderId: '1046328657587',
    projectId: 'fir-report-17f69',
    storageBucket: 'fir-report-17f69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNt91D6jy8eLjqD7iMXdawjR-CL6IVGJc',
    appId: '1:1046328657587:ios:6de57e4ec0f1ac246192c6',
    messagingSenderId: '1046328657587',
    projectId: 'fir-report-17f69',
    storageBucket: 'fir-report-17f69.firebasestorage.app',
    iosBundleId: 'com.example.sReportSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNt91D6jy8eLjqD7iMXdawjR-CL6IVGJc',
    appId: '1:1046328657587:ios:6de57e4ec0f1ac246192c6',
    messagingSenderId: '1046328657587',
    projectId: 'fir-report-17f69',
    storageBucket: 'fir-report-17f69.firebasestorage.app',
    iosBundleId: 'com.example.sReportSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_ikhLuRa6f402i828yEX5dhrrj3n2NBQ',
    appId: '1:1046328657587:web:f5bed7b2e0eea5a06192c6',
    messagingSenderId: '1046328657587',
    projectId: 'fir-report-17f69',
    authDomain: 'fir-report-17f69.firebaseapp.com',
    storageBucket: 'fir-report-17f69.firebasestorage.app',
    measurementId: 'G-SZZ03ZE0W1',
  );
}
